<?php
$servername = "sql109.ihweb.ir";
$username = "ihweb_31084399";
$password = "17m3fsnt";
$dbname= "ihweb_31084399_main";
// Create connection
$conn = new mysqli($servername, $username, $password,$dbname);

// Check connection
if ($conn->connect_error) {
  die("Connection failed: " . $conn->connect_error);
}
 $author_name=null;
// echo "Connected successfully <br>";
echo "<h3>View comments for movie ".$_GET["film_name"]."</h3><br>";
$lang="Select";
?>

<html>                   
    <body>                   
    <form action="second.php?film_name=<?php echo $_GET['film_name'] ?>" method="post">
  <label for="language">Choose a language:</label>
  <select id="language" name="language">
    <option value="Select" selected >Select language</option>
    <option value="English">English</option>
    <option value="Spanish" >Spanish</option>
    <option value="French">French</option>
    <option value="German">German</option>
  </select>
  <input type="submit">
</form>

<?php

$sql = "SELECT id,film, name, text FROM comments";
$result = $conn->query($sql);
$lang= $_POST["language"];
// echo "<br>".$lang."<br>";

$idx=0;



if ($lang!="Select"  && $lang!=null && $result->num_rows > 0) {


  while($row = $result->fetch_assoc()) {
    


    if ($row["film"] != $_GET["film_name"])
    {
        continue;
    }
   
    $com=$comments[$idx];
    

    $payload="";

    switch ($lang) {
    case "English":
        break;
        
    case "Spanish":
        $payload="{\"text\": [\""   .$row["text"]." \"], \"model_id\":\"en-es\"}";
        break;
    case "German":
        $payload="{\"text\": [\""   .$row["text"]." \"], \"model_id\":\"en-de\"}";
        break;
     case "French":
        $payload="{\"text\": [\""   .$row["text"]." \"], \"model_id\":\"en-fr\"}";
        break;
    }
    
    if ($lang != "English"){

    
    // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
    $ch = curl_init();

    curl_setopt($ch, CURLOPT_URL, 'https://api.us-south.language-translator.watson.cloud.ibm.com/instances/68951c15-5ae3-46fd-bd90-858e10d7697d/v3/translate?version=2018-05-01');
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_POST, 1);


    curl_setopt($ch, CURLOPT_POSTFIELDS, $payload);
    curl_setopt($ch, CURLOPT_USERPWD, 'apikey' . ':' . 'PFkbvgxFBsq2uoM7VHdF54M5Rvo2HDvVl6N31504HOIb');
 
    $headers = array();
    $headers[] = 'Content-Type: application/json';
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
     
    $res = curl_exec($ch);

    $res= json_decode($res);

    $translation=$res->translations[0]->translation. "<br>";
    }

    else{
        $translation=$row["text"];
    }

    echo "<b>".$row["name"] .":</b> ".$translation."<br>";

    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    curl_close($ch);

    $idx++;
  }

} 

?>

    </body>
</html>



